spring.application.name=MoneyTrack

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.access-token-expiration-ms=7200000
jwt.refresh-token-expiration-ms=604800000

# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/moneytrack
# spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=moneytrack_user
spring.datasource.password=moneytrack_password

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
